//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ablative.
        /// </summary>
        public static string Ablative {
            get {
                return ResourceManager.GetString("Ablative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos de projet.
        /// </summary>
        public static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qui somme nous?.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objectif.
        /// </summary>
        public static string Aim {
            get {
                return ResourceManager.GetString("Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type d’alignement.
        /// </summary>
        public static string AlignmentType {
            get {
                return ResourceManager.GetString("AlignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allatif.
        /// </summary>
        public static string Allative {
            get {
                return ResourceManager.GetString("Allative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Et.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous sûr de vouloir supprimer ceci?.
        /// </summary>
        public static string AskDelete {
            get {
                return ResourceManager.GetString("AskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre akṣara par ligne.
        /// </summary>
        public static string AvCharPerLigne {
            get {
                return ResourceManager.GetString("AvCharPerLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bibliographie.
        /// </summary>
        public static string Bibliography {
            get {
                return ResourceManager.GetString("Bibliography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La Bibliothèque nationale de France.
        /// </summary>
        public static string bnf {
            get {
                return ResourceManager.GetString("bnf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cas.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Causative.
        /// </summary>
        public static string Causative {
            get {
                return ResourceManager.GetString("Causative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chinoise.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index de code.
        /// </summary>
        public static string CodeIndex {
            get {
                return ResourceManager.GetString("CodeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partenaires.
        /// </summary>
        public static string Collaboration {
            get {
                return ResourceManager.GetString("Collaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborateur.
        /// </summary>
        public static string Collaborator {
            get {
                return ResourceManager.GetString("Collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonds.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comitative.
        /// </summary>
        public static string Comitative {
            get {
                return ResourceManager.GetString("Comitative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complet.
        /// </summary>
        public static string Completeness {
            get {
                return ResourceManager.GetString("Completeness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nouveau mot de passe et le mot de passe de confirmation ne correspondent pas..
        /// </summary>
        public static string ConfirmError {
            get {
                return ResourceManager.GetString("ConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez le mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conjugaison.
        /// </summary>
        public static string Conjugation {
            get {
                return ResourceManager.GetString("Conjugation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message Utilisateur.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe actuel.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;activité.
        /// </summary>
        public static string DateActivity {
            get {
                return ResourceManager.GetString("DateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Modifier.
        /// </summary>
        public static string DateModifier {
            get {
                return ResourceManager.GetString("DateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dérivé de.
        /// </summary>
        public static string DerivedFrom {
            get {
                return ResourceManager.GetString("DerivedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dictionnaire Tocharian.
        /// </summary>
        public static string DictionaryTocharian {
            get {
                return ResourceManager.GetString("DictionaryTocharian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distance du trou d’enfilage marge gauche.
        /// </summary>
        public static string DistanceStringholeLeft {
            get {
                return ResourceManager.GetString("DistanceStringholeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distance du trou d’enfilage marge droite.
        /// </summary>
        public static string DistanceStringholeRight {
            get {
                return ResourceManager.GetString("DistanceStringholeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Éditeur.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courrier électronique.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglaise.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Équivalent dans une autre langue.
        /// </summary>
        public static string EquivalentInOther {
            get {
                return ResourceManager.GetString("EquivalentInOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Équivalent en TA.
        /// </summary>
        public static string EquivalentInTA {
            get {
                return ResourceManager.GetString("EquivalentInTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code d&apos;expédition.
        /// </summary>
        public static string ExpeditionCode {
            get {
                return ResourceManager.GetString("ExpeditionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact pratique.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} est obligatoire..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La forme.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Française.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le financement.
        /// </summary>
        public static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat général.
        /// </summary>
        public static string GeneralState {
            get {
                return ResourceManager.GetString("GeneralState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Génitive.
        /// </summary>
        public static string Genitive {
            get {
                return ResourceManager.GetString("Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allemande.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour  .
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HisTochText dans la presse.
        /// </summary>
        public static string HisTochTextPress {
            get {
                return ResourceManager.GetString("HisTochTextPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page Principale.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instrumental.
        /// </summary>
        public static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voyelle de racine interne.
        /// </summary>
        public static string InternalRootVowel {
            get {
                return ResourceManager.GetString("InternalRootVowel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lignes interrompues.
        /// </summary>
        public static string InterruptedLine {
            get {
                return ResourceManager.GetString("InterruptedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Japonaise.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joint.
        /// </summary>
        public static string Joint {
            get {
                return ResourceManager.GetString("Joint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails d&apos;état de langue.
        /// </summary>
        public static string LanguageAdd {
            get {
                return ResourceManager.GetString("LanguageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État de langue.
        /// </summary>
        public static string LanguageStage {
            get {
                return ResourceManager.GetString("LanguageStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom .
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise en page.
        /// </summary>
        public static string LayoutManuscript {
            get {
                return ResourceManager.GetString("LayoutManuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de feuilles.
        /// </summary>
        public static string LeafNumber {
            get {
                return ResourceManager.GetString("LeafNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Savoir Plus.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interligne.
        /// </summary>
        public static string LineDistance {
            get {
                return ResourceManager.GetString("LineDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List des Messages Contact.
        /// </summary>
        public static string ListContact {
            get {
                return ResourceManager.GetString("ListContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locative.
        /// </summary>
        public static string Locative {
            get {
                return ResourceManager.GetString("Locative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu principal.
        /// </summary>
        public static string MainContent {
            get {
                return ResourceManager.GetString("MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu principal.
        /// </summary>
        public static string MainContents {
            get {
                return ResourceManager.GetString("MainContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de trouvaille principal.
        /// </summary>
        public static string MainFindSpot {
            get {
                return ResourceManager.GetString("MainFindSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion Manuscript.
        /// </summary>
        public static string ManagementManuscript {
            get {
                return ResourceManager.GetString("ManagementManuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion Page.
        /// </summary>
        public static string ManagementPage {
            get {
                return ResourceManager.GetString("ManagementPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion Utilisateurs.
        /// </summary>
        public static string ManagementUsers {
            get {
                return ResourceManager.GetString("ManagementUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manuscrite.
        /// </summary>
        public static string Manuscript {
            get {
                return ResourceManager.GetString("Manuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Support.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1-1500 caractères.
        /// </summary>
        public static string MaxLength10000 {
            get {
                return ResourceManager.GetString("MaxLength10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1-1500 caractères.
        /// </summary>
        public static string MaxLength1500 {
            get {
                return ResourceManager.GetString("MaxLength1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0}  doit avoir number caractères moins de 20.
        /// </summary>
        public static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1-2000 Characters.
        /// </summary>
        public static string MaxLength2000 {
            get {
                return ResourceManager.GetString("MaxLength2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0}  doit avoir number caractères moins de 30.
        /// </summary>
        public static string MaxLength30 {
            get {
                return ResourceManager.GetString("MaxLength30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0}  doit avoir number caractères moins de 40.
        /// </summary>
        public static string MaxLength40 {
            get {
                return ResourceManager.GetString("MaxLength40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1-500 caractères.
        /// </summary>
        public static string MaxLength500 {
            get {
                return ResourceManager.GetString("MaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forme métrique.
        /// </summary>
        public static string MetricForm {
            get {
                return ResourceManager.GetString("MetricForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0}  doit avoir au moins de 2 caractères.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Hauteur.
        /// </summary>
        public static string ModuleHeight {
            get {
                return ResourceManager.GetString("ModuleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Largeur.
        /// </summary>
        public static string ModuleWidth {
            get {
                return ResourceManager.GetString("ModuleWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        public static string NameActivity {
            get {
                return ResourceManager.GetString("NameActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Nombre de lignes doit être positif.
        /// </summary>
        public static string NegativeError {
            get {
                return ResourceManager.GetString("NegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau mot de passe.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelles.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelles&amp;Blog.
        /// </summary>
        public static string News_Blog {
            get {
                return ResourceManager.GetString("News_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Journal.
        /// </summary>
        public static string Newspaper {
            get {
                return ResourceManager.GetString("Newspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur du trait.
        /// </summary>
        public static string NibThickness {
            get {
                return ResourceManager.GetString("NibThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nominate.
        /// </summary>
        public static string Nominate {
            get {
                return ResourceManager.GetString("Nominate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de lignes.
        /// </summary>
        public static string NumberOfLine {
            get {
                return ResourceManager.GetString("NumberOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oblique.
        /// </summary>
        public static string Oblique {
            get {
                return ResourceManager.GetString("Oblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bureau.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} ne doit contenir que des lettres.
        /// </summary>
        public static string OnlyLetters {
            get {
                return ResourceManager.GetString("OnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} ne doit contenir que des chiffres.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autres Cote.
        /// </summary>
        public static string OtherSiglum {
            get {
                return ResourceManager.GetString("OtherSiglum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page Nouvelles.
        /// </summary>
        public static string PageNews {
            get {
                return ResourceManager.GetString("PageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Papier couleur.
        /// </summary>
        public static string PaperColor {
            get {
                return ResourceManager.GetString("PaperColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Epaisseur du papier.
        /// </summary>
        public static string PaperThickness {
            get {
                return ResourceManager.GetString("PaperThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paradigme.
        /// </summary>
        public static string Paradigm {
            get {
                return ResourceManager.GetString("Paradigm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parallèles.
        /// </summary>
        public static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passage.
        /// </summary>
        public static string Passage {
            get {
                return ResourceManager.GetString("Passage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perlative.
        /// </summary>
        public static string Perlative {
            get {
                return ResourceManager.GetString("Perlative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire philologique.
        /// </summary>
        public static string PhilologicalCommentary {
            get {
                return ResourceManager.GetString("PhilologicalCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phrase.
        /// </summary>
        public static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lieu.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présentation Projet HISTOCHTEXT.
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programmation.
        /// </summary>
        public static string Programing {
            get {
                return ResourceManager.GetString("Programing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La provenance.
        /// </summary>
        public static string Provenience {
            get {
                return ResourceManager.GetString("Provenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de publication.
        /// </summary>
        public static string PublicationDate {
            get {
                return ResourceManager.GetString("PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publications.
        /// </summary>
        public static string Publications {
            get {
                return ResourceManager.GetString("Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publié par.
        /// </summary>
        public static string PublishedBy {
            get {
                return ResourceManager.GetString("PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lexèmes connexes.
        /// </summary>
        public static string RelatedLexemes {
            get {
                return ResourceManager.GetString("RelatedLexemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remarques supplémentaires.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dépôt.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenir.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caractère racine.
        /// </summary>
        public static string RootCharacter {
            get {
                return ResourceManager.GetString("RootCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réglure.
        /// </summary>
        public static string Ruling {
            get {
                return ResourceManager.GetString("Ruling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleur de la réglure.
        /// </summary>
        public static string RulingColor {
            get {
                return ResourceManager.GetString("RulingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réglure détail.
        /// </summary>
        public static string RulingDetail {
            get {
                return ResourceManager.GetString("RulingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Écriture.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Écriture Détaille.
        /// </summary>
        public static string ScriptAdd {
            get {
                return ResourceManager.GetString("ScriptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ecriture manuscrit.
        /// </summary>
        public static string ScriptManuscript {
            get {
                return ResourceManager.GetString("ScriptManuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultats de votre recherche.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de recherche.
        /// </summary>
        public static string SearchWord {
            get {
                return ResourceManager.GetString("SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Savoir également.
        /// </summary>
        public static string SeeAlso {
            get {
                return ResourceManager.GetString("SeeAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date envoi.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer un email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cote bibliothèque.
        /// </summary>
        public static string Shelfmark {
            get {
                return ResourceManager.GetString("Shelfmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cote.
        /// </summary>
        public static string Siglum {
            get {
                return ResourceManager.GetString("Siglum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S’inscrire.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Singulière.
        /// </summary>
        public static string Singular {
            get {
                return ResourceManager.GetString("Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille Hauteur.
        /// </summary>
        public static string SizeHeight {
            get {
                return ResourceManager.GetString("SizeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille Largeur.
        /// </summary>
        public static string SizeWidth {
            get {
                return ResourceManager.GetString("SizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu spécifique de trouvaille.
        /// </summary>
        public static string SpecificFindSpot {
            get {
                return ResourceManager.GetString("SpecificFindSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Radical.
        /// </summary>
        public static string Stem {
            get {
                return ResourceManager.GetString("Stem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class de radical.
        /// </summary>
        public static string StemClass {
            get {
                return ResourceManager.GetString("StemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur de la réserve du trou d’enfilage.
        /// </summary>
        public static string StringholeHeight {
            get {
                return ResourceManager.GetString("StringholeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur de la réserve du trou d’enfilage.
        /// </summary>
        public static string StringholeWidth {
            get {
                return ResourceManager.GetString("StringholeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résumé.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notre equipe.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Genre de texte.
        /// </summary>
        public static string TextGenre {
            get {
                return ResourceManager.GetString("TextGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous-genre du texte.
        /// </summary>
        public static string TextSubgenre {
            get {
                return ResourceManager.GetString("TextSubgenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M/Mme.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titres de l&apos;article.
        /// </summary>
        public static string TitleArticle {
            get {
                return ResourceManager.GetString("TitleArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TochPhrase.
        /// </summary>
        public static string TochPhrase {
            get {
                return ResourceManager.GetString("TochPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TochHistoire.
        /// </summary>
        public static string TochStory {
            get {
                return ResourceManager.GetString("TochStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transcription.
        /// </summary>
        public static string Transcription {
            get {
                return ResourceManager.GetString("Transcription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translitération.
        /// </summary>
        public static string Transliteration {
            get {
                return ResourceManager.GetString("Transliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mélodie.
        /// </summary>
        public static string Tune {
            get {
                return ResourceManager.GetString("Tune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vietnamien .
        /// </summary>
        public static string VietNamese {
            get {
                return ResourceManager.GetString("VietNamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Des vues.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vocabulaire.
        /// </summary>
        public static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vocative.
        /// </summary>
        public static string Vocative {
            get {
                return ResourceManager.GetString("Vocative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voix.
        /// </summary>
        public static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classe de mots.
        /// </summary>
        public static string WordClass {
            get {
                return ResourceManager.GetString("WordClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mots.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous-classe de mots.
        /// </summary>
        public static string WordSubClass {
            get {
                return ResourceManager.GetString("WordSubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outil d’écriture.
        /// </summary>
        public static string WritingTool {
            get {
                return ResourceManager.GetString("WritingTool", resourceCulture);
            }
        }
    }
}
