namespace Horizone.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class changeDic : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.DictionaryTocharians", "TochCorrespondence", c => c.String());
            AddColumn("dbo.ReverseDictionaries", "SymbolPrefix", c => c.String());
            AddColumn("dbo.ReverseDictionaries", "SymbolSufix", c => c.String());
            DropColumn("dbo.DictionaryTocharians", "NominateMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "NominateMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "NominateMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "NominateFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "NominateFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "NominateFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "NominateNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "NominateNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "NominateNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "ObliqueMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "ObliqueMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "ObliqueMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "ObliqueFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "ObliqueFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "ObliqueFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "ObliqueNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "ObliqueNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "ObliqueNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "VocativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "VocativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "VocativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "VocativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "VocativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "VocativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "VocativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "VocativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "VocativeNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "GenitiveMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "GenitiveMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "GenitiveMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "GenitiveFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "GenitiveFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "GenitiveFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "GenitiveNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "GenitiveNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "GenitiveNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "LocativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "LocativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "LocativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "LocativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "LocativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "LocativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "LocativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "LocativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "LocativeNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "AblativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "AblativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "AblativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "AblativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "AblativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "AblativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "AblativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "AblativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "AblativeNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "AllativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "AllativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "AllativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "AllativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "AllativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "AllativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "AllativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "AllativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "AllativeNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "PerlativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "PerlativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "PerlativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "PerlativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "PerlativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "PerlativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "PerlativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "PerlativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "PerlativeNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "InstrumentalNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "ComitativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "ComitativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "ComitativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "ComitativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "ComitativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "ComitativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "ComitativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "ComitativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "ComitativeNeuterPlural");
            DropColumn("dbo.DictionaryTocharians", "CausativeMasculineSingular");
            DropColumn("dbo.DictionaryTocharians", "CausativeMasculineDual");
            DropColumn("dbo.DictionaryTocharians", "CausativeMasculinePlural");
            DropColumn("dbo.DictionaryTocharians", "CausativeFeminineSingular");
            DropColumn("dbo.DictionaryTocharians", "CausativeFeminineDual");
            DropColumn("dbo.DictionaryTocharians", "CausativeFemininePlural");
            DropColumn("dbo.DictionaryTocharians", "CausativeNeuterSingular");
            DropColumn("dbo.DictionaryTocharians", "CausativeNeuterDual");
            DropColumn("dbo.DictionaryTocharians", "CausativeNeuterPlural");
        }
        
        public override void Down()
        {
            AddColumn("dbo.DictionaryTocharians", "CausativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "CausativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ComitativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "InstrumentalMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "PerlativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AllativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "AblativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "LocativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "GenitiveMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "VocativeMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "ObliqueMasculineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateNeuterPlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateNeuterDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateNeuterSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateFemininePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateFeminineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateFeminineSingular", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateMasculinePlural", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateMasculineDual", c => c.String());
            AddColumn("dbo.DictionaryTocharians", "NominateMasculineSingular", c => c.String());
            DropColumn("dbo.ReverseDictionaries", "SymbolSufix");
            DropColumn("dbo.ReverseDictionaries", "SymbolPrefix");
            DropColumn("dbo.DictionaryTocharians", "TochCorrespondence");
        }
    }
}
